version: "3.1"
services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      default:
        ipv4_address: 172.18.1.2
  mongo-db:
    image: mongo:3.6
    hostname: mongo-db
    container_name: db-mongo
    ports:
        - "27017:27017"
    networks:
      default:
        ipv4_address: 172.18.1.3
    command: --bind_ip_all --smallfiles
    volumes:
      - mongo-db:/data

  orion:
    image: fiware/orion
    container_name: fiware-orion
    depends_on:
        - mongo-db
    networks:
      default:
        ipv4_address: 172.18.1.4
    expose:
        - "1026"
    ports:
        - "1026:1026"
    command: -dbhost mongo-db -logLevel DEBUG

  iot-agent:
    image: fiware/iotagent-ul
    hostname: iot-agent
    container_name: fiware-iot-agent
    depends_on:
      - mongo-db
      - mosquitto
    networks:
      default:
        ipv4_address: 172.18.1.5
    expose:
      - "4041"
    ports:
      - "4041:4041"
    environment:
      - "IOTA_CB_HOST=orion" # name of the context broker to update context
      - "IOTA_CB_PORT=1026" # port the context broker listens on to update context
      - "IOTA_NORTH_PORT=4041"
      - "IOTA_REGISTRY_TYPE=mongodb" #Whether to hold IoT device info in memory or in a database
      - "IOTA_LOG_LEVEL=DEBUG" #The log level of the IoT Agent
      - "IOTA_TIMESTAMP=true"
      - "IOTA_MONGO_HOST=mongo-db" # The host name of ongoDB
      - "IOTA_MONGO_PORT=27017" # The port mongoDB is listening on
      - "IOTA_MONGO_DB=iotagentul" # The name of the database used in mongoDB
      - "IOTA_MQTT_HOST=mosquitto" # The host name of the MQTT Broker
      - "IOTA_MQTT_PORT=1883" # The port the MQTT Broker is listening on to receive topics 
      - "IOTA_PROVIDER_URL=http://iot-agent:4041"

  cygnus:
    image: fiware/cygnus-ngsi:latest
    hostname: cygnus
    container_name: fiware-cygnus
    depends_on:
        - mongo-db
    networks:
      default:
        ipv4_address: 172.18.1.6
    expose:
        - "5080"
    ports:
        - "5050:5050"
        - "5080:5080"
    environment:
        - "CYGNUS_MONGO_HOSTS=mongo-db:27017"
        - "CYGNUS_LOG_LEVEL=DEBUG"
        - "CYGNUS_SERVICE_PORT=5050"
        - "CYGNUS_API_PORT=5080"

networks:
  default:
    ipam:
      config:
        - subnet: 172.18.1.0/24
volumes:
  mongo-db:

