#!/bin/bash
#
#  Command Line Interface to start all services associated with the Getting-Started Tutorial
#
#  For this tutorial the commands are merely a convenience script to run docker-compose
#
set -e
if (( $# != 1 )); then
    echo "Illegal number of parameters"
    echo "usage: services [create|start|stop]"
    exit 1
fi
command="$1"
case "${command}" in
        "help")
        echo "usage: services [create|start|stop]"
        ;;
    "start")
                echo -e "Starting the following 7 modules"
                echo -e "- \033[1;34mOrion\033[0m is the context broker"
                echo -e "- \033[1;36mIoT-Agent\033[0m is configured for the UltraLight Protocol"
                echo -e "- \033[1;30mMosquitto\033[0m acts as an MQTT Message Broker"
                echo -e "- \033[1;31mCygnus\033[0m acts as a Historical Data Manager"
                echo -e "- \033[1;32mSquid\033[0m acts as a Reverse TSL Proxy"
                echo -e "- \033[1;33mKeyroc\033[0m acts as an Identity Management Front-End"
                echo ""
                docker-compose --log-level ERROR -p fiware up -d --remove-orphans
                ;;
        "stop")
                echo "stopping containers"
                docker-compose --log-level ERROR -p fiware down -v --remove-orphans
                ;;
        "create")
                echo "Obtaining Mongo DB 3.6 image"
                docker pull mongo:3.6
                echo "Obtaining Latest Orion Image"
                docker pull fiware/orion
                echo "Obtaining Latest UltraLight IoT Agent"
                docker pull fiware/iotagent-ul
                echo "Obtaining Latest Mosquitto Message Broker"
                docker pull eclipse-mosquitto
                echo "Obtaining Latest Cygnus"
                docker pull fiware/cygnus-ngsi
                echo "Obtaining Latest Squid"
        		docker build -t sameersbn/squid github.com/sameersbn/docker-squid
                echo "Obtaining MySQL 5.7 image"
                docker pull mysql:5.7
                echo "Obtaining Latest Keyrock Image"
                docker pull fiware/idm
                ;;
        *)
                echo "Command not Found."
                echo "usage: services [create|start|stop]"
                exit 127;
                ;;
esac
